"""
This is a setup.py script generated by py2applet

Usage:
    python3.6 setup.py py2app
"""

from setuptools import setup

APP = ['Soundgrain.py']
APP_NAME = 'Soundgrain'
DATA_FILES = ['Resources/']
OPTIONS = {'argv_emulation': False,
           #'strip': False, # only for debugging purposes.
           'iconfile': 'Resources/SoundGrain.icns',
           'includes': 'wx.adv,wx.html,wx.xml'}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
