import os

os.system("python ..\pyinstaller\Configure.py")
os.system('python ..\pyinstaller\Makespec.py -F -c --icon=Resources\SoundGrain.ico "SoundGrain.py"')
os.system('python ..\pyinstaller\Build.py "SoundGrain.spec"')
os.system("svn export . SoundGrain_Win")
os.system("copy dist\SoundGrain.exe SoundGrain_Win /Y")
os.system("copy scripts\README.txt SoundGrain_Win /Y")
os.system("rmdir /Q /S SoundGrain_Win\scripts")
os.remove("SoundGrain_Win/SoundGrain.py")
os.remove("SoundGrain_Win/Resources/SoundGrain.icns")
os.remove("SoundGrain.spec")
os.remove("warnSoundGrain.txt")
os.system("rmdir /Q /S buildSoundGrain")
#os.system("PAComp -r -p SoundGrain_Win-2.0.zip SoundGrain_Win\*")
#os.system("rmdir /Q /S SoundGrain")
os.system("rmdir /Q /S build")
os.system("rmdir /Q /S dist")
